[project]
name = "naturalization-civic-qa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "streamlit>=1.45.1",
    "watchdog>=6.0.0",
]
